# train_aug_obb.yaml — Ultralytics YOLOv8-OBB
mode: train
task: obb

data: path/to/your/modified-DOTA/data.yaml
model: path/to/your/yolov8-obb(default)_backbone.yaml
epochs: 150
imgsz: 928
batch: 4
device: 0
patience: 0

optimizer: AdamW
lr0: 0.01
lrf: 0.01
momentum: 0.937
weight_decay: 0.0005

# Augmentation (default)
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
degrees: 0
translate: 0.10
scale: 0.50
shear: 0
perspective: 0.0
flipud: 0
fliplr: 0.5
bgr: 0.0
mosaic: 1.0
mixup: 0.0


save: true
project: runs/train/final_config
name: final_config_method3
